// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: sicynjtefomzfihluffg

class SupabaseConfig {
  static const String supabaseUrl = 'https://sicynjtefomzfihluffg.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpY3luanRlZm9temZpaGx1ZmZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMDIyMTYsImV4cCI6MjA4Njg3ODIxNn0.poISJJJHEb1oiVnFI_2Wo5sxHB3bvh0xaLU4LRagVkQ';
}
